### ISSUE TITLE
Pre-trained weights file couldn't be downloaded

### ISSUE THREAD

**Issue by XuyangPan** [Niwhskal/SRNet#12]

**Comment by XuyangPan** [comment]
hello, Niwhskal, Thank you for the amazing work, I  wanna to get results through your code like yours. But pre-trained weights file couldn't download,  
Could you send the weights file to my email or tell me a solution to get weights? 
Really appreciate! 
XuyangPan@yeah.net

**Comment by Niwhskal** [comment]
Sure. Let me know of a platform that I can upload it on.

**Comment by XuyangPan** [comment]
> Sure. Let me know of a platform that I can upload it on.

Thanks for your reply. Email is a good choice.

XuyangPan@yeah.net

**Comment by XuyangPan** [comment]
The figure below is my training result following your default configuration. At this moment in time, I don't know what my solution will be.

training result
![ret](https://user-images.githubusercontent.com/39898699/113228909-822c7c00-92c8-11eb-8507-123a8f817efd.jpg)

**Comment by vince2003** [comment]
Hello @Niwhskal and @XuyangPan,
Can you sent Pre-trained weights to my email: quangvinh242003@gmail.com
Thank you in advance!

**Comment by CalmCapK** [comment]
@Niwhskal  Hello, I am very interested in your work, but the pre-training weights are no longer valid. Could you send the weights file to my email: calmcapk@gmail.com ?
Really appreciate !!!

**Comment by surongwei** [comment]
Hello @Niwhskal and @XuyangPan,
Can you sent Pre-trained weights to my email: su_rongwei@126.com
Thank you very much!

**Comment by ltm920716** [comment]
hello @XuyangPan @Niwhskal ，

Could you please share a new link for the Pre-trained weight，or send me the model？

my email：804884774@qq.com or ltmcumtcs@163.com
Thank you very much！

**Comment by romanticegg** [comment]
hello @XuyangPan @Niwhskal 
Could you please give us the way to download the pretrained weights, or send me the model?
my email: 1015072920@qq.com
Thanks very much!

**Comment by FBEMPSS** [comment]
hello @XuyangPan @Niwhskal 
Could you please send me the pretrained model, as the download link is invalid?
my email: 1240883540@qq.com
Thanks very much!

**Comment by Niwhskal** [comment]
Links have been updated. Check readme.
