### ISSUE TITLE
能不能使用这个网络将有风格的字体图像朝着标准字体学习。

### ISSUE THREAD

**Issue by xuefanfu** [Niwhskal/SRNet#13]
能不能使用这个网络将有风格的字体图像朝着标准字体学习，我试着更改了一下数据集，但是发现无法生成。请问您有什么好的方法吗？

**Comment by Niwhskal** [comment]
You should be able to. But training the Srnet from scratch is incredibly difficult. It's notoriously unstable. You'd have to spend a lot of time monitoring the training process.

**Comment by xuefanfu** [comment]
> You should be able to. But training the Srnet from scratch is incredibly difficult. It's notoriously unstable. You'd have to spend a lot of time monitoring the training process.

Thanks for your help.
