### ISSUE TITLE
These two links cannot be opened, can you send me the content or dataset of these two links? @Niwhskal 

### ISSUE THREAD

**Issue by pengyaru** [Niwhskal/SRNet#16]
http://www.robots.ox.ac.uk/~vgg/data/scenetext/preproc/imnames.cp 
http://www.robots.ox.ac.uk/~vgg/data/scenetext/preproc/bg_img.tar.gz
These two links cannot be opened, can you send me the content or dataset of these two links? @Niwhskal

**Comment by pengyaru** [comment]
It appears in data_script.sh  and can you send me them? @Niwhskal

**Comment by ltm920716** [comment]
@pengyaru 
https://github.com/ankush-me/SynthText

**Comment by Niwhskal** [comment]
Updated.
