### ISSUE TITLE
  Questions about this command “$ ./data_script.sh”

### ISSUE THREAD

**Issue by heping0307** [Niwhskal/SRNet#20]
We can't download the two data you said。
http://www.robots.ox.ac.uk/~vgg/data/scenetext/preproc/imnames.cp
http://www.robots.ox.ac.uk/~vgg/data/scenetext/preproc/bg_img.tar.gz

**Comment by ltm920716** [comment]
@heping0307 
https://github.com/ankush-me/SynthText

**Comment by Niwhskal** [comment]
Links have been updated.
