### ISSUE TITLE
about F.to_pil_image

### ISSUE THREAD

**Issue by CCC-123** [Niwhskal/SRNet#4]
Hi, i encounter some problem in image saving.
https://github.com/Niwhskal/SRNet/blob/30bb6a5370b2a087e87ac71e255272491c87f1c6/predict.py#L88-L90
I found in F.to_pil_image it multiplies with 255 if input is floattensor, and save result will be noise.
And
```
 o_t = F.to_pil_image((o_t + 1)/2)
``` 
will work.

**Comment by Niwhskal** [comment]
True, this is a bug. Thanks for pointing it out. . I've updated the predict file.
